version: "3.7"
services:
  app:
    container_name: winov-fullstack-test-backend-app-dev
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    image: ejklock/winov-tasks:1.0
    networks:
      - winov-fullstack-test-backendNetwork
    restart: unless-stopped

    working_dir: /var/www/app
  db:
    command: --default-authentication-plugin=mysql_native_password
    container_name: winov-fullstack-test-backend-dev-db
    environment:
      MYSQL_DATABASE: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: app
      MYSQL_USER: app
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    image: mysql:5.7
    networks:
      - winov-fullstack-test-backendNetwork
    ports:
      - 33306:3306
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - winov-fullstack-test-backendMysqlData:/var/lib/mysql
  nginx:
    container_name: winov-fullstack-test-backend-dev-nginx
    image: nginx:alpine
    networks:
      - winov-fullstack-test-backendNetwork
    ports:
      - 8000:80
    restart: unless-stopped
    volumes:
      - ./:/var/www/app
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    working_dir: /var/www/app
networks:
  winov-fullstack-test-backendNetwork:
    driver: bridge
volumes:
  winov-fullstack-test-backendMysqlData:
    driver: local
    name: winov-fullstack-test-backendMysqlData
